//>>built
require({cache:{"JBrowse/Store/SeqFeature/BAM/Util":function(){define(["jszlib/inflate","jszlib/arrayCopy","JBrowse/Util"],function(p,q,e){var o=e.fastDeclare({constructor:function(c,i){this.block=c;this.offset=i},toString:function(){return""+this.block+":"+this.offset},cmp:function(c){return c.block-this.block||c.offset-this.offset}}),l={readInt:function(c,i){return c[i+3]<<24|c[i+2]<<16|c[i+1]<<8|c[i]},readShort:function(c,i){return c[i+1]<<8|c[i]},readFloat:function(c,i){for(var e=new Uint8Array(4),
j=0;4>j;j++)e[j]=c[i+j];return(new Float32Array(e.buffer))[0]},readVirtualOffset:function(c,i){var e=4294967296*(c[i+6]&255)+16777216*(c[i+5]&255)+65536*(c[i+4]&255)+256*(c[i+3]&255)+(c[i+2]&255),j=c[i+1]<<8|c[i];return 0==e&&0==j?null:new o(e,j)},unbgzf:function(c,e){for(var e=Math.min(e||Infinity,c.byteLength-27),m=[],j=0,b=[0];b[0]<e;b[0]+=8){var f=new Uint8Array(c,b[0],18);if(!(31==f[0]&&139==f[1])){console.error("invalid BGZF block header, skipping",f);break}var f=l.readShort(f,10),f=b[0]+12+
f,a;try{a=p(c,f,c.byteLength-f,b)}catch(n){if(/^Z_BUF_ERROR/.test(n.statusString)&&m.length)break;else throw n;}a.byteLength&&(j+=a.byteLength,m.push(a))}if(1==m.length)return m[0];j=new Uint8Array(j);for(a=b=0;a<m.length;++a)f=new Uint8Array(m[a]),q(f,0,j,b,f.length),b+=f.length;return j.buffer}};return l})},"JBrowse/Store/SeqFeature/BAM/File":function(){define("dojo/_base/declare,dojo/_base/array,JBrowse/Util,JBrowse/Store/LRUCache,./Util,./LazyFeature".split(","),function(p,q,e,o,l,c){function i(a,
b){var d,g=[];--b;g.push(0);for(d=1+(a>>26);d<=1+(b>>26);++d)g.push(d);for(d=9+(a>>23);d<=9+(b>>23);++d)g.push(d);for(d=73+(a>>20);d<=73+(b>>20);++d)g.push(d);for(d=585+(a>>17);d<=585+(b>>17);++d)g.push(d);for(d=4681+(a>>14);d<=4681+(b>>14);++d)g.push(d);return g}var m=function(){console.error.apply(console,arguments)},j=e.fastDeclare({constructor:function(a,b,d){this.minv=a;this.maxv=b;this.bin=d},toString:function(){return this.minv+".."+this.maxv+" (bin "+this.bin+")"}}),b=l.readInt,f=l.readVirtualOffset;
return p(null,{constructor:function(a){this.store=a.store;this.data=a.data;this.bai=a.bai},init:function(a){var b=a.success||function(){},d=a.failure||function(){};this._readBAI(dojo.hitch(this,function(){this._readBAMheader(function(){b()},d)}),d)},_readBAI:function(a,n){this.bai.fetch(dojo.hitch(this,function(d){if(d)if(Uint8Array){var g=new Uint8Array(d);if(21578050!=b(g,0))m("Not a BAI file"),n("Not a BAI file");else{var k=b(g,4);this.indices=[];for(var h=8,r=0;r<k;++r){for(var s=h,e=b(g,h),h=
h+4,c=0;c<e;++c){b(g,h);for(var i=b(g,h+4),h=h+8,j=0;j<i;j++)this._findMinAlignment(f(g,h)),h+=16}c=b(g,h);h+=4;this._findMinAlignment(c?f(g,h):null);h+=8*c;if(0<e||0<c)this.indices[r]=new Uint8Array(d,s,h-s)}this.empty=!this.indices.length;a(this.indices,this.minAlignmentVO)}}else m("Browser does not support typed arrays"),n("Browser does not support typed arrays");else m("No data read from BAM index (BAI) file"),n("No data read from BAM index (BAI) file")}),n)},_findMinAlignment:function(a){if(a&&
(!this.minAlignmentVO||0>this.minAlignmentVO.cmp(a)))this.minAlignmentVO=a},_readBAMheader:function(a,n){var d=this;d.data.read(0,d.minAlignmentVO?d.minAlignmentVO.block+65535:null,function(g){g=l.unbgzf(g);g=new Uint8Array(g);if(21840194!=b(g,0))m("Not a BAM file"),n("Not a BAM file");else{var k=b(g,4);d.data.read(0,k+8+65536,function(g){var g=l.unbgzf(g),g=new Uint8Array(g),n=b(g,k+8),f=k+12;d.chrToIndex={};d.indexToChr=[];for(var c=0;c<n;++c){for(var e=b(g,f),i="",j=0;j<e-1;++j)i+=String.fromCharCode(g[f+
4+j]);j=b(g,f+e+4);d.chrToIndex[i]=c;0==i.indexOf("chr")?d.chrToIndex[i.substring(3)]=c:d.chrToIndex["chr"+i]=c;d.indexToChr.push({name:i,length:j});f=f+8+e}a()},n)}},n)},blocksForRange:function(a,n,d){var g=this.indices[a];if(!g)return[];for(var a=i(n,d),k=[],h=0;h<a.length;++h)k[a[h]]=!0;for(var a=[],c=[],h=b(g,0),e=4,l=0;l<h;++l){var m=b(g,e),o=b(g,e+4),e=e+8;if(k[m])for(var p=0;p<o;++p){var q=f(g,e),t=f(g,e+8);(4681>m?c:a).push(new j(q,t,m));e+=16}else e+=16*o}h=b(g,e);k=null;n=Math.min(n>>14,
h-1);d=Math.min(d>>14,h-1);for(h=n;h<=d;++h)if((n=f(g,e+4+8*h))&&(!k||n.block<k.block||n.offset<k.offset))k=n;g=[];if(null!=k)for(h=0;h<c.length;++h)d=c[h],d.maxv.block>=k.block&&d.maxv.offset>=k.offset&&g.push(d);c=g;g=[];for(h=0;h<c.length;++h)g.push(c[h]);for(h=0;h<a.length;++h)g.push(a[h]);g.sort(function(a,b){var d=a.minv.block-b.minv.block;return 0!=d?d:a.minv.offset-b.minv.offset});a=[];if(0<g.length){c=g[0];for(h=1;h<g.length;++h)d=g[h],d.minv.block==c.maxv.block?c=new j(c.minv,d.maxv,"linear"):
(a.push(c),c=d);a.push(c)}return a},fetch:function(a,b,d,g){var f=this.chrToIndex&&this.chrToIndex[a];0<=f?(a=this.blocksForRange(f,b,d))||g(null,"Error in index fetch"):a=[];a.toString=function(){return this.join(", ")};try{this._fetchChunkFeatures(a,function(a,h){h?g(null,h):(a=q.filter(a,function(a){return!(a.get("end")<b||a.get("start")>d)&&(void 0===f||a._refID==f)}),g(a))})}catch(h){g(null,h)}},_fetchChunkFeatures:function(a,b){if(a.length){var d=[],g=0,f=this.featureCache=this.featureCache||
new o({name:"bamFeatureCache",fillCallback:dojo.hitch(this,"_readChunk"),sizeFunction:function(a){return a.length},maxSize:1E5}),h;q.forEach(a,function(c){f.get(c,function(f,c){h=h||c;d.push.apply(d,f);++g==a.length&&b(d,h)})})}else b([])},_readChunk:function(a,b){var d=this,g=[],f=a.minv.block;d.data.read(f,a.maxv.block+65536-f+1,function(f){try{var c=l.unbgzf(f,a.maxv.block-a.minv.block+1);d.readBamFeatures(new Uint8Array(c),a.minv.offset,g,b)}catch(k){b(null,k)}})},readBamFeatures:function(a,f,
d,g){for(var k=this,h=0;;)if(f>=a.length){g(d);break}else if(300>=h){var e=b(a,f),e=f+4+e-1;if(e<a.length){var i=new c({store:this.store,file:this,bytes:{byteArray:a,start:f,end:e}});d.push(i);h++}f=e+1}else{window.setTimeout(function(){k.readBamFeatures(a,f,d,g)},1);break}}})})},"JBrowse/Store/SeqFeature/BAM/LazyFeature":function(){define(["dojo/_base/array","JBrowse/Util","./Util","JBrowse/Model/SimpleFeature"],function(p,q,e,o){var l="=,A,C,x,G,x,x,x,T,x,x,x,x,x,x,N".split(","),c="M,I,D,N,S,H,P,=,X,?,?,?,?,?,?,?".split(","),
i=e.readInt,m=e.readShort,j=e.readFloat;return q.fastDeclare({constructor:function(b){this.store=b.store;this.file=b.file;this.data={type:"match",source:b.store.source};this.bytes={start:b.bytes.start,end:b.bytes.end,byteArray:b.bytes.byteArray};this._coreParse()},get:function(b){return this._get(b.toLowerCase())},_get:function(b){return b in this.data?this.data[b]:this.data[b]=this[b]?this[b]():this._flagMasks[b]?this._parseFlag(b):this._parseTag(b)},tags:function(){return this._get("_tags")},_tags:function(){this._parseAllTags();
var b=["seq","seq_reverse_complemented","unmapped"];this._get("unmapped")||b.push("start","end","strand","score","qual","MQ","CIGAR","length_on_ref");this._get("multi_segment_template")&&b.push("multi_segment_all_aligned","multi_segment_next_segment_unmapped","multi_segment_next_segment_reversed","multi_segment_first","multi_segment_last","secondary_alignment","qc_failed","duplicate","next_segment_position");var b=b.concat(this._tagList||[]),f=this.data,a;for(a in f)f.hasOwnProperty(a)&&"_"!=a[0]&&
b.push(a);var c={};return b=p.filter(b,function(a){if(a in this.data&&void 0===this.data[a])return!1;var a=a.toLowerCase(),b=c[a];c[a]=!0;return!b},this)},parent:function(){},children:function(){return this._get("subfeatures")},id:function(){return this._get("name")+"/"+this._get("md")+"/"+this._get("cigar")+"/"+this._get("start")},mq:function(){var b=(this._get("_bin_mq_nl")&65280)>>8;return 255==b?void 0:b},score:function(){return this._get("mq")},qual:function(){if(!this._get("unmapped")){for(var b=
[],f=this.bytes.byteArray,a=this.bytes.start+36+this._get("_l_read_name")+4*this._get("_n_cigar_op")+this._get("_seq_bytes"),c=this._get("seq_length"),d=0;d<c;++d)b.push(f[a+d]);return b.join(" ")}},strand:function(){var b=this._get("xs");return b?"-"==b?-1:1:this._get("seq_reverse_complemented")?-1:1},_l_read_name:function(){return this._get("_bin_mq_nl")&255},_seq_bytes:function(){return this._get("seq_length")+1>>1},seq:function(){for(var b="",f=this.bytes.byteArray,a=this.bytes.start+36+this._get("_l_read_name")+
4*this._get("_n_cigar_op"),c=this._get("_seq_bytes"),d=0;d<c;++d)var g=f[a+d],b=b+l[(g&240)>>4],b=b+l[g&15];return b},name:function(){return this._get("_read_name")},_read_name:function(){for(var b=this.bytes.byteArray,f="",a=this._get("_l_read_name"),c=this.bytes.start+36,d=0;d<a-1;++d)f+=String.fromCharCode(b[c+d]);return f},_n_cigar_op:function(){return this._get("_flag_nc")&65535},cigar:function(){if(!this._get("unmapped")){for(var b=this.bytes.byteArray,f=this._get("_n_cigar_op"),a=this.bytes.start+
36+this._get("_l_read_name"),e="",d=0,g=0;g<f;++g)var k=i(b,a),h=k>>4,e=e+h+c[k&15],d=d+h,a=a+4;this.data.length_on_ref=d;return e}},next_segment_position:function(){var b=this.file.indexToChr[this._get("_next_refid")];if(b)return b.name+":"+this._get("_next_pos")},subfeatures:function(){if(this.store.createSubfeatures){var b=this._get("cigar");if(b)return this._cigarToSubfeats(b)}},length_on_ref:function(){this._get("cigar");return this.data.length_on_ref},_flags:function(){return(this.data._flag_nc&
4294901760)>>16},end:function(){return this._get("start")+(this._get("length_on_ref")||this._get("seq_length")||void 0)},seq_id:function(){return this._get("unmapped")?void 0:(this.file.indexToChr[this._refID]||{}).name},_coreParse:function(){for(var b=this.bytes.byteArray,f=this.bytes.start+4,a=new Uint8Array(32),c=0;32>c;c++)a[c]=b[c+f];b=new Int32Array(a.buffer);f=this.data;this._refID=b[0];f.start=b[1];f._bin_mq_nl=b[2];f._flag_nc=b[3];f.seq_length=b[4];f._next_refid=b[5];f._next_pos=b[6];f.template_length=
b[7]},_parseTag:function(b){if(!this._allTagsParsed){this._tagList=this._tagList||[];for(var f=this.bytes.byteArray,a=this._tagOffset||this.bytes.start+36+this._get("_l_read_name")+4*this._get("_n_cigar_op")+this._get("_seq_bytes")+this._get("seq_length"),c=this.bytes.end;a<c&&g!=b;){var d=String.fromCharCode(f[a],f[a+1]),g=d.toLowerCase(),e=String.fromCharCode(f[a+2]),a=a+3;switch(e.toLowerCase()){case "a":e=String.fromCharCode(f[a]);a+=1;break;case "i":e=i(f,a);a+=4;break;case "c":e=f[a];a+=1;break;
case "s":e=m(f,a);a+=2;break;case "f":e=j(f,a);a+=4;break;case "z":case "h":for(e="";a<=c;){var h=f[a++];if(0==h)break;else e+=String.fromCharCode(h)}break;default:console.warn("Unknown BAM tag type '"+e+"', tags may be incomplete"),e=void 0,a=c}this._tagOffset=a;this._tagList.push(d);if(g==b)return e;this.data[g]=e}this._allTagsParsed=!0}},_parseAllTags:function(){this._parseTag()},_flagMasks:{multi_segment_template:1,multi_segment_all_aligned:2,unmapped:4,multi_segment_next_segment_unmapped:8,seq_reverse_complemented:16,
multi_segment_next_segment_reversed:32,multi_segment_first:64,multi_segment_last:128,secondary_alignment:256,qc_failed:512,duplicate:1024},_parseFlag:function(b){return!!(this._get("_flags")&this._flagMasks[b])},_parseCigar:function(b){return p.map(b.match(/\d+\D/g),function(b){return[b.match(/\D/)[0].toUpperCase(),parseInt(b)]})},_cigarToSubfeats:function(b){for(var c=[],a=this._get("start"),e,b=this._parseCigar(b),d=0;d<b.length;d++){var g=b[d][1],k=b[d][0];"="===k&&(k="E");switch(k){case "M":case "D":case "N":case "E":case "X":e=
a+g;break;case "I":e=a}"N"!==k&&(a=new o({data:{type:k,start:a,end:e,strand:this._get("strand"),cigar_op:g+k},parent:this}),c.push(a));a=e}return c}})})},"JBrowse/Model/SimpleFeature":function(){define(["JBrowse/Util"],function(p){var q=0;return p.fastDeclare({constructor:function(e){e=e||{};this.data=e.data||{};this._uniqueID=e.id||"SimpleFeature_"+q++;this._parent=e.parent},get:function(e){return this.data[e]},set:function(e,o){this.data[e]=o},tags:function(){var e=[],o=this.data,l;for(l in o)o.hasOwnProperty(l)&&
e.push(l);return e},id:function(e){if(e)this._uniqueID=e;return this._uniqueID},parent:function(){return this._parent},children:function(){return this.get("subfeatures")}})})}}});
define("JBrowse/Store/SeqFeature/BAM","dojo/_base/declare,dojo/_base/array,dojo/_base/Deferred,dojo/_base/lang,JBrowse/Util,JBrowse/Store/SeqFeature,JBrowse/Store/DeferredStatsMixin,JBrowse/Store/DeferredFeaturesMixin,JBrowse/Model/XHRBlob,./BAM/Util,./BAM/File".split(","),function(p,q,e,o,l,c,i,m,j,b,f){return p([c,i,m],{constructor:function(a){this.createSubfeatures=a.subfeatures;var b=a.bam||function(){var b=l.resolveUrl(a.baseUrl||"/",l.fillTemplate(a.urlTemplate||"data.bam",{refseq:(this.refSeq||
{}).name}));return new j(b)}.call(this),d=a.bai||function(){var b=l.resolveUrl(a.baseUrl||"/",l.fillTemplate(a.baiUrlTemplate||a.urlTemplate+".bai"||"data.bam.bai",{refseq:(this.refSeq||{}).name}));return new j(b)}.call(this);this.bam=new f({store:this,data:b,bai:d});this.source=(b.url?b.url.match(/\/([^/\#\?]+)($|[\#\?])/)[1]:b.blob?b.blob.name:void 0)||void 0;this.bam.init({success:dojo.hitch(this,"_estimateGlobalStats",dojo.hitch(this,function(a){a?this._failAllDeferred(a):(this._deferred.stats.resolve({success:!0}),
this._deferred.features.resolve({success:!0}))})),failure:dojo.hitch(this,"_failAllDeferred")})},_estimateGlobalStats:function(a){var b=function(a,b,d){var c=0.75*a.start+0.25*a.end,e=Math.max(0,Math.round(c-b/2)),f=Math.min(Math.round(c+b/2),a.end);this.bam.fetch(a.name,e,f,dojo.hitch(this,function(c,i){i?(console.error(i),d.call(this,b,null,i)):c&&(c=q.filter(c,function(a){return a.get("start")>=e&&a.get("end")<=f}),d.call(this,b,{featureDensity:c.length/b,_statsSampleFeatures:c.length,_statsSampleInterval:{ref:a.name,
start:e,end:f,length:b}}))}))},d=function(c,e,f){if(f)a(f);else{var i=this.refSeq.end-this.refSeq.start;300<=e._statsSampleFeatures||2*c>i||f?(this.globalStats=e,a()):b.call(this,this.refSeq,2*c,d)}};b.call(this,this.refSeq,100,d)},_getFeatures:function(a,b,d,c){var e=a.start,f=a.end;this.bam.fetch(this.refSeq.name,e,f,function(a,i){if(i)console.error("error fetching BAM data: "+i),c&&c(i);else if(a){var j=0,l=function(){for(;j<a.length;j++){var i=a[j];if(!i.get("unmapped")&&!(i.get("end")<=e||i.get("start")>=
f))try{b(i)}catch(m){c?c(m):console.error(m,m.stack);return}if(j&&!(j%300)){window.setTimeout(l,1);j++;break}}j>=a.length&&d()};l()}})}})});