//>>built
require({cache:{"JBrowse/Store/SeqFeature/BigWig":function(){define("dojo/_base/declare,dojo/_base/lang,dojo/_base/array,dojo/_base/url,JBrowse/Store/SeqFeature,JBrowse/Store/DeferredStatsMixin,JBrowse/Store/DeferredFeaturesMixin,./BigWig/Window,JBrowse/Util,JBrowse/Model/XHRBlob".split(","),function(g,o,f,j,m,i,h,r,b,d){return g([m,i,h],{BIG_WIG_MAGIC:-2003829722,BIG_BED_MAGIC:-2021002517,BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(a){var c;if(!(c=a.blob))c=
b.resolveUrl(a.baseUrl||"/",b.fillTemplate(a.urlTemplate||"data.bigwig",{refseq:(this.refSeq||{}).name})),c=new d(c);this.data=c;this.name=a.name||this.data.url&&(new j(this.data.url)).path.replace(/^.+\//,"")||"anonymous";this._load()},_getGlobalStats:function(a){var c=this._stats||{};if(!("scoreMean"in c))c.scoreMean=c.scoreSum/c.basesCovered;if(!("scoreStdDev"in c))c.scoreStdDev=this._calcStdFromSums(c.scoreSum,c.scoreSumSquares,c.basesCovered);a(c)},_calcStdFromSums:function(a,c,b){a=c-a*a/b;
1<b&&(a/=b-1);return 0>a?0:Math.sqrt(a)},_load:function(){var a=this;a.data.slice(0,512).fetch(function(c){if(c){a.fileSize=c.fileSize;var b=new Int16Array(c),e=new Int32Array(c);if(e[0]==a.BIG_WIG_MAGIC)a.type="bigwig";else if(e[0]==a.BIG_BED_MAGIC)a.type="bigbed";else{console.error("Format "+e[0]+" not supported");a._failAllDeferred("Format "+e[0]+" not supported");return}a.version=b[2];a.numZoomLevels=b[3];a.chromTreeOffset=e[2]<<32|e[3];a.unzoomedDataOffset=e[4]<<32|e[5];a.unzoomedIndexOffset=
e[6]<<32|e[7];a.fieldCount=b[16];a.definedFieldCount=b[17];a.asOffset=e[9]<<32|e[10];a.totalSummaryOffset=e[11]<<32|e[12];a.uncompressBufSize=e[13];a.zoomLevels=[];for(b=0;b<a.numZoomLevels;++b)a.zoomLevels.push({reductionLevel:e[6*b+16],dataOffset:e[6*b+18]<<32|e[6*b+19],indexOffset:e[6*b+20]<<32|e[6*b+21]});a.totalSummaryOffset?Float64Array?function(){var b=new Uint32Array(c,a.totalSummaryOffset,2),e=new Float64Array(c,a.totalSummaryOffset+8,4);a._stats={basesCovered:b[0]<<32|b[1],scoreMin:e[0],
scoreMax:e[1],scoreSum:e[2],scoreSumSquares:e[3]}}.call():console.warn("BigWig "+a.data.url+" total summary not available, this web browser is not capable of handling this data type."):console.warn("BigWig "+a.data.url+" has no total summary data.");a._readChromTree(function(){a._deferred.features.resolve({success:!0});a._deferred.stats.resolve({success:!0})})}else this._failAllDeferred("BBI header not readable")},dojo.hitch(this,"_failAllDeferred"))},_readInt:function(a,b){return a[b+3]<<24|a[b+
2]<<16|a[b+1]<<8|a[b]},_readShort:function(a,b){return a[b+1]<<8|a[b]},_readChromTree:function(a){var b=this;this.chromsToIDs={};this.idsToChroms={};for(var d=this.unzoomedDataOffset;0!=d%4;)++d;var e=this._readInt,j=this._readShort;this.data.slice(this.chromTreeOffset,d-this.chromTreeOffset).fetch(function(d){if(!Uint8Array||!Int16Array||!Int32Array)b._loading.resolve({success:!1,error:"Browser does not support typed arrays"});else{var n=new Uint8Array(d),d=new Int32Array(d,0,6);if(2026540177!==
d[0])throw"parse error: not a Kent bPlusTree";var f=d[2],m=function(a){if(a>=n.length)throw"reading beyond end of buffer";for(var d=n[a],v=j(n,a+2),a=a+4,i=0;i<v;++i)if(d){for(var h="",s=0;s<f;++s){var g=n[a++];0!=g&&(h+=String.fromCharCode(g))}s=e(n,a);e(n,a+4);a+=8;b.chromsToIDs[h]=s;0==h.indexOf("chr")&&(b.chromsToIDs[h.substr(3)]=s);b.idsToChroms[s]=h}else a+=f,h=e(n,a+4)<<32|e(n,a),a+=8,h-=b.chromTreeOffset,m(h)};m(32);a.call(b,b)}})},_getFeatures:function(a,b,d,e){var j=a.ref,m=a.start,h=a.end;
(a=a.basesPerSpan?this.getView(1/a.basesPerSpan):a.scale?this.getView(scale):this.getView(1))?a.readWigData(j,m,h,dojo.hitch(this,function(a){f.forEach(a||[],b);d()}),e):d()},getUnzoomedView:function(){if(!this.unzoomedView){var a=4E3;this.zoomLevels[0]&&(a=this.zoomLevels[0].dataOffset-this.unzoomedIndexOffset);this.unzoomedView=new r(this,this.unzoomedIndexOffset,a,!1)}return this.unzoomedView},getView:function(a){if(!this.zoomLevels||!this.zoomLevels.length)return null;if(!this._viewCache||this._viewCache.scale!=
a)this._viewCache={scale:a,view:this._getView(a)};return this._viewCache.view},_getView:function(a){for(var a=1/a,b=this.zoomLevels.length-1;0<b;b--){var d=this.zoomLevels[b];if(d&&d.reductionLevel<=a)return new r(this,d.indexOffset,b<this.zoomLevels.length-1?this.zoomLevels[b+1].dataOffset-d.indexOffset:this.fileSize-4-d.indexOffset,!0)}return this.getUnzoomedView()}})})},"JBrowse/Store/SeqFeature/BigWig/Window":function(){define(["dojo/_base/declare","dojo/_base/lang","./RequestWorker"],function(g,
o,f){return g(null,{constructor:function(j,f,i,h){this.bwg=j;this.cirTreeOffset=f;this.cirTreeLength=i;this.isSummary=h},BED_COLOR_REGEXP:/^[0-9]+,[0-9]+,[0-9]+/,readWigData:function(f,m,i,h){f=this.bwg.chromsToIDs[f];void 0===f?h([]):this.readWigDataById(f,m,i,h)},readWigDataById:function(j,m,i,h){this.cirHeader?(new f(this,j,m,i,h)).cirFobRecur([this.cirTreeOffset+48],1):(j=o.hitch(this,"readWigDataById",j,m,i,h),this.cirHeaderLoading?this.cirHeaderLoading.push(j):(this.cirHeaderLoading=[j],this.bwg.data.slice(this.cirTreeOffset,
48).fetch(o.hitch(this,function(f){this.cirHeader=f;this.cirBlockSize=(new Int32Array(this.cirHeader,0,2))[1];dojo.forEach(this.cirHeaderLoading,function(b){b()});delete this.cirHeaderLoading}))))}})})},"JBrowse/Store/SeqFeature/BigWig/RequestWorker":function(){define(["dojo/_base/declare","dojo/_base/lang","JBrowse/Model/Range","jszlib/inflate"],function(g,o,f,j){var m=function(){console.log.apply(console,arguments)},i=g(null,{get:function(b){return this[{start:"min",end:"max",seq_id:"segment"}[b]||
b]},tags:function(){return"start,end,seq_id,score,type,source".split(",")}}),h=g(i,{}),r=g(i,{});return g(null,{BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(b,d,a,c,f){this.window=b;this.source=b.bwg.name||void 0;this.blocksToFetch=[];this.outstanding=0;this.chr=d;this.min=a;this.max=c;this.callback=f},cirFobRecur:function(b,d){this.outstanding+=b.length;for(var a=4+32*this.window.cirBlockSize,c,n=0;n<b.length;++n){var e=new f(b[n],Math.min(b[n]+a,this.window.cirTreeOffset+
this.window.cirTreeLength));c=c?c.union(e):e}a=c.ranges();for(c=0;c<a.length;++c)this.cirFobStartFetch(b,a[c],d)},cirFobStartFetch:function(b,d,a){d.max();d.min();this.window.bwg.data.slice(d.min(),d.max()-d.min()).fetch(o.hitch(this,function(c){for(var f=0;f<b.length;++f)d.contains(b[f])&&(this.cirFobRecur2(c,b[f]-d.min(),a),--this.outstanding,0==this.outstanding&&this.cirCompleted())}))},cirFobRecur2:function(b,d,a){var c=new Int8Array(b),f=new Int16Array(b),b=new Int32Array(b),c=c[d],f=f[d/2+1],
d=d+4;if(0!=c)for(c=0;c<f;++c){var e=d/4,j=b[e],m=b[e+1],h=b[e+2],l=b[e+3],i=b[e+4]<<32|b[e+5],a=b[e+6]<<32|b[e+7];(j<this.chr||j==this.chr&&m<=this.max)&&(h>this.chr||h==this.chr&&l>=this.min)&&this.blocksToFetch.push({offset:i,size:a});d+=32}else{for(var g=[],c=0;c<f;++c)e=d/4,j=b[e],m=b[e+1],h=b[e+2],l=b[e+3],i=b[e+4]<<32|b[e+5],(j<this.chr||j==this.chr&&m<=this.max)&&(h>this.chr||h==this.chr&&l>=this.min)&&g.push(i),d+=24;0<g.length&&this.cirFobRecur(g,a+1)}},cirCompleted:function(){this.blocksToFetch.sort(function(b,
d){return(b.offset|0)-(d.offset|0)});0==this.blocksToFetch.length?this.callback([]):(this.features=[],this.tramp())},createFeature:function(b,d,a){a||(a={});var c=new h;c.segment=this.window.bwg.idsToChroms[this.chr];c.min=b;c.max=d;c.type="remark";c.source=this.source;for(k in a)c[k]=a[k];this.features.push(c)},maybeCreateFeature:function(b,d,a){b<=this.max&&d>=this.min&&this.createFeature(b,d,a)},tramp:function(){if(0==this.blocksToFetch.length)this.callback(this.features);else{var b=this.blocksToFetch[0];
if(b.data){var d=new Uint8Array(b.data);if(this.window.isSummary)for(var a=new Int16Array(b.data),c=new Int32Array(b.data),h=new Float32Array(b.data),d=b.data.byteLength/32,a=0;a<d;++a){var e=c[8*a],b=c[8*a+1],i=c[8*a+2],g=c[8*a+3],u=h[8*a+6];if(e==this.chr){e={score:u/g};if("bigbed"==this.window.bwg.type)e.type="density";this.maybeCreateFeature(b,i,e)}}else if("bigwig"==this.window.bwg.type)if(a=new Int16Array(b.data),c=new Int32Array(b.data),h=new Float32Array(b.data),e=c[0],b=c[1],e=c[3],i=c[4],
g=d[20],d=a[11],g==this.BIG_WIG_TYPE_FSTEP)for(a=0;a<d;++a)g=h[a+6],this.maybeCreateFeature(b+a*e,b+a*e+i,{score:g});else if(g==this.BIG_WIG_TYPE_VSTEP)for(a=0;a<d;++a)b=c[2*a+6],g=h[2*a+7],this.maybeCreateFeature(b,b+i,{score:g});else if(g==this.BIG_WIG_TYPE_GRAPH)for(a=0;a<d;++a)b=c[3*a+6],i=c[3*a+7],g=h[3*a+8],b>i&&(b=i),this.maybeCreateFeature(b,i,{score:g});else m("Currently not handling bwgType="+g);else if("bigbed"==this.window.bwg.type)for(c=0;c<d.length;){e=d[c+3]<<24|d[c+2]<<16|d[c+1]<<
8|d[c+0];b=d[c+7]<<24|d[c+6]<<16|d[c+5]<<8|d[c+4];i=d[c+11]<<24|d[c+10]<<16|d[c+9]<<8|d[c+8];c+=12;for(a="";;)if(h=d[c++],0!=h)a+=String.fromCharCode(h);else break;var h={},l=a.split("\t");if(0<l.length)h.label=l[0];if(1<l.length)h.score=stringToInt(l[1]);if(2<l.length)h.orientation=l[2];if(5<l.length&&(a=l[5],this.window.BED_COLOR_REGEXP.test(a)))h.override_color="rgb("+a+")";if(9>l.length)e==this.chr&&this.maybeCreateFeature(b,i,h);else if(e==this.chr&&b<=this.max&&i>=this.min){i=l[3]|0;e=l[4]|
0;a=l[6]|0;g=l[7].split(",");u=l[8].split(",");h.type="bb-transcript";var p=new r;p.id=l[0];p.type="bb-transcript";p.notes=[];h.groups=[p];if(10<l.length){var p=l[9],l=l[10],q=new r;q.id=p;q.label=l;q.type="gene";h.groups.push(q)}l=null;for(p=0;p<a;++p)q=(u[p]|0)+b,q=new f(q,q+(g[p]|0)),l=l?l.union(q):q;g=l.ranges();for(b=0;b<g.length;++b)a=g[b],this.createFeature(a.min(),a.max(),h);if(e>i&&(b=l.intersection(new f(i,e)))){h.type="bb-translation";i=b.ranges();for(b=0;b<i.length;++b)a=i[b],this.createFeature(a.min(),
a.max(),h)}}}else m("Don't know what to do with "+this.window.bwg.type);this.blocksToFetch.splice(0,1);this.tramp()}else{for(var d=b.offset,t=b.size,b=1;b<this.blocksToFetch.length&&this.blocksToFetch[b].offset==d+t;)t+=this.blocksToFetch[b].size,++b;this.window.bwg.data.slice(d,t).fetch(o.hitch(this,function(a){for(var b=0,c=0;b<t;){var d=this.blocksToFetch[c],e;0<this.window.bwg.uncompressBufSize?e=j(a,b+2,d.size-2):(e=new Uint8Array(d.size),arrayCopy(new Uint8Array(a,b,d.size),0,e,0,d.size),e=
e.buffer);d.data=e;b+=d.size;++c}this.tramp()}))}}}})})},"JBrowse/Model/Range":function(){define(["dojo/_base/declare"],function(g){var o=g(null,{constructor:function(){this._ranges=2==arguments.length?[{min:arguments[0],max:arguments[1]}]:0 in arguments[0]?dojo.clone(arguments[0]):[arguments[0]]},min:function(){return this._ranges[0].min},max:function(){return this._ranges[this._ranges.length-1].max},contains:function(f){for(var j=0;j<this._ranges.length;++j){var g=this._ranges[j];if(g.min<=f&&g.max>=
f)return!0}return!1},isContiguous:function(){return 1<this._ranges.length},ranges:function(){return this._ranges.map(function(f){return new o(f.min,f.max)})},toString:function(){return this._ranges.map(function(f){return"["+f.min+"-"+f.max+"]"}).join(",")},union:function(f){for(var f=this.ranges().concat(f.ranges()).sort(this.rangeOrder),j=[],g=f[0],i=1;i<f.length;++i){var h=f[i];h.min()>g.max()+1?(j.push(g),g=h):h.max()>g.max()&&(g=new o(g.min(),h.max()))}j.push(g);return 1==j.length?j[0]:new _Compound(j)},
intersection:function(f){for(var g,m=this.ranges(),i=f.ranges(),h=m.length,r=i.length,b=0,d=0,a=[];b<h&&d<r;){g=m[b];var f=i[d],c=Math.max(g.min(),f.min()),n=Math.min(g.max(),f.max());n>=c&&a.push(new o(c,n));g.max()>f.max()?++d:++b}return 0==a.length?null:1==a.length?a[0]:new _Compound(a)},coverage:function(){for(var f=0,g=this.ranges(),m=0;m<g.length;++m)var i=g[m],f=f+(i.max()-i.min()+1);return f},rangeOrder:function(f,g){2>arguments.length&&(g=f,f=this);return f.min()<g.min()?-1:f.min()>g.min()?
1:f.max()<g.max()?-1:g.max()>f.max()?1:0}});return o})}}});define("JBrowse/Store/BigWig",["JBrowse/Store/SeqFeature/BigWig"],function(g){return g});